# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'IceCreamParlor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IceCreamParlor
  pod 'Alamofire', '~> 5.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'IceCreamParlorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
